# get base image from my repo
FROM jenkins/jenkins:lts

MAINTAINER Adam Pratt

# switch to root to install other tools
USER root

# set environment variables
ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"


# Make directory for 'sp_cmdln.zip'
# Copy file from host dir to '/sp_cmd' filepath on container and unzip
RUN mkdir sp_cmd
COPY ~/Devopsadmin/sp_cmdln.zip /sp_cmd
RUN cd sp_cmd
RUN unzip sp_cmd/sp_cmdln.zip -d sp_cmd
ENV PATH "$PATH:/sp_cmd"

# PLUGINS PLUGINS
COPY plugins.txt /usr/share/jenkins/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/plugins.txt
RUN REF_DIR=${REF:-/var/lib/jenkins/plugins}





# update package mgr
RUN apt-get update

# install nodejs
RUN apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_9.x | bash
RUN apt-get install -y nodejs
RUN curl -L https://www.npmjs.com/install.sh | sh
RUN apt-get install -y subversion


# install angular/cli
RUN npm install -g @angular/cli@6.2.7

# install docker
RUN yum update -y
RUN yum install -y docker-engine
RUN service docker start

# Clean up and remove any unused packages
RUN apt-get clean
RUN apt-get autoremove


# drop back to the regular jenkins user - good practice
# USER jenkins